quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=CinemaAdmin
quarkus.datasource.password=luka1103

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/CinemaBase
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8081

quarkus.oidc.auth-server-url=http://localhost:8080/realms/cinema
quarkus.oidc.client-id=cinema-client
quarkus.oidc.credentials.secret=5DTAJSuoWeGONMMaKDIy8cBeTSxzHRvn
quarkus.oidc.tls.verification=none